#!/bin/bash

## Vérifier si le dossier existe, sinon le créer ##
if [ ! -d ~/.quitter ]
then
mkdir ~/.quitter
fi

## On se place dans le dossier ##
cd ~/.quitter

## Stocker les variables entrées par l'utilisateur ##
heureRDV=$1
comentUSER=$2

## On regarde ce que l'utilisateur a entré et on en déduit les fonctions à éxecuter ##
case $heureRDV in

-q)
cat boucle.pid | 
kill -9
;;

-l)
cat horaires.db
;;

-r)
echo "supprimer"
;;

esac


#if [ $# -ne 2 ]
#then    
#     echo "Vous devez saisir 2 paramètres: heure (HHMM) et 'commentaire'"
#    echo "** -q: arrête la boucle, -l: affiche les rdv, -r HHMM supprime un rdv **"
#    exit 2
#fi


## Stockage des données utlisateur dans le fichier ##
echo "$heureRDV: $comentUSER" >> ~/.quitter/horaires.db

## On clacule le nombre de lignes du document ##
nbLignes=$(< horaires.db wc -l)
echo $nbLignes

## Début de la boucle infinie qui rappelle le rdv lorsque l'heure est arrivée ##
while [ $nbLignes -ne 0 ]
do
    echo $! > boucle.pid
    sleep 30
    for i in $(seq 1 $nbLignes)
    do
        horaire=$(sed "${i}q;d" horaires.db | cut -d: -f1)
        date=$(date +%H%M)
        message=$(sed "${i}q;d" horaires.db)
        if [ $date = $horaire ]
        then
        xmessage $message -buttons FERMER
        sed -i "${i}d" horaires.db
        nbLignes=$(< horaires.db wc -l)
        fi
    done
done