#!/bin/bash

## Vérifier si le dossier existe, sinon le créer ##
if [ ! -d ~/.quitter ]
then
mkdir ~/.quitter
fi

## On se place dans le dossier ##
cd ~/.quitter
touch boucle.pid

## On regarde ce que l'utilisateur a entré et on en déduit les fonctions à éxecuter ##
##if [ $# -e 1 ]
##then
case $1 in

-q)
kill -9 | cat boucle.pid
rm boucle.pid
;;

-l)
cat horaires.db
;;

esac

##else if [ $# -e 2 ]
##then
## Stockage données utilisateur ##
heureRDV=$1
commentUSER=$2

case $1 in

-r)
grep $2 | sed -i d horaires.db
echo "supprimé"
;;

esac


#if [ $# -ne 2 ]
#then    
#     echo "Vous devez saisir 2 paramètres: heure (HHMM) et 'commentaire'"
#    echo "** -q: arrête la boucle, -l: affiche les rdv, -r HHMM supprime un rdv **"
#    exit 2
#fi


## Stockage des données utlisateur dans le fichier ##
echo "$heureRDV: $comentUSER" >> ~/.quitter/horaires.db

## On calcule le nombre de lignes du document ##
nbLignes=$(< horaires.db wc -l)

## Fonction de la boucle infinie qui rappelle le rdv lorsque l'heure est arrivée ##
function boucle
{
while [ $nbLignes -ne 0 ]
do
echo $$ > boucle.pid
    sleep 30
    for i in $(seq 1 $nbLignes)
    do
        horaire=$(sed "${i}q;d" horaires.db | cut -d: -f1)
        date=$(date +%H%M)
        message=$(sed "${i}q;d" horaires.db)
        if [ $date = $horaire ]
        then
        xmessage $message -buttons FERMER
        sed -i "${i}d" horaires.db
        nbLignes=$(< horaires.db wc -l)
        fi
    done
done
}

## Lancement de la boucle ##
if [ -s boucle.pid ]
then
echo "Boucle déjà lancée"
else
boucle
fi